Template fix
SciGaP/gsu-gateway-theme pull request #1
Opened 2018-01-11 17:25 UTC by stephenpaul2727

Embedded the information from https://help.rs.gsu.edu/display/PD/ACoRE on the partials template.
Linked to live page: https://hpcgateway.gsu.edu/

2018-01-11 17:37 UTC, machristie requested changes
Thanks Stephen. In general looks good, I just have a couple suggestions.

2018-01-11 17:37 UTC, machristie commented on assets/css/style.css
> +    padding-bottom: 2%";
You've got an extra double quote there.

2018-01-11 17:37 UTC, machristie commented on partials/template.blade.php
> +			<img class="center-image img-responsive" src="/assets/img/orion.png">
I think they want to link to the live image, not a static one. Same deal on line 83.

2018-01-11 19:33 UTC, stephenpaul2727 commented
Hi Marcus, I have made the requested changes. I had left the other two images as static because, I cannot find a live link for them when i inspect the page.

Here is a inspection of outer html:

<img class="confluence-embedded-image image-center" width="400" src="/download/attachments/26017795/Architecture-Orion%20v5.jpg?version=1&amp;modificationDate=1502301698392&amp;api=v2" data-image-src="/download/attachments/26017795/Architecture-Orion%20v5.jpg?version=1&amp;modificationDate=1502301698392&amp;api=v2" data-unresolved-comment-count="0" data-linked-resource-id="26607623" data-linked-resource-version="1" data-linked-resource-type="attachment" data-linked-resource-default-alias="Architecture-Orion v5.jpg" data-base-url="https://help.rs.gsu.edu" data-linked-resource-content-type="image/jpeg" data-linked-resource-container-id="26017795" data-linked-resource-container-version="11">

As you can see its pointing to confluence download folder. so I went with downloading the image and serving it as static. Is this okay? Thanks

2018-01-11 20:03 UTC, machristie commented
Hi @stephenpaul2727 , got it. I was looking at a page with Eroma yesterday and she had live links on the page.

@eroma2014 can you get the URLs to Stephen? Does he have a different link than we were looking at yesterday?

2018-01-16 19:08 UTC, machristie approved these changes

2018-01-16 19:08 UTC, merged